
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true
    avoid_void_async: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    always_declare_return_types: true
    use_super_parameters: false

analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
    invalid_annotation_target: ignore
